### ISSUE TITLE
The new update: unknown error

### ISSUE THREAD

**Issue by seghier** [ForNeVeR/xaml-math#416] opened 2023-06-11 19:16 UTC
Hi, Thank you for the new release but sadly it works then an error appears

![image](https://github.com/ForNeVeR/xaml-math/assets/6026588/dc958fca-7900-4849-b235-8b8e80c8e783)

`1. I/O error occurred. (line: 0)`

The same codes works fine with the previous release

**Comment by ForNeVeR** [comment] 2023-06-11 19:32
Do you have a stacktrace of the error?

**Comment by ForNeVeR** [comment] 2023-06-11 19:39
I wasn't successful in reproducing the problem in both .NET 7 and .NET Framework 4.8 WPF projects using a freshly released package, so far. Everything seems to work fine for me :(

**Comment by seghier** [comment] 2023-06-11 19:56
I also don't know where the problem is.
I use Rhino and Grasshopper , the plugins works at first time then this error appears and no other description available.
I will use the previous version until i find the problem

**Comment by seghier** [comment] 2023-06-11 20:13
It work again, i need more tests the coming days to see if the problem disappears definitely

**Comment by ForNeVeR** [comment] 2023-06-11 20:32
I understand that you integrate XAML-Math's C# API with some graphical "blueprint-like" programming/workflow environment, but I've never used those things myself, and so can't advise on how to debug the code generated there.

I've genuinely taken a look at the latest changes and tried reproducing the issue in different combinations of things I control, to no avail so far.

I'd be glad to help if there are any additional details, or it stops working again.

For now, let's close this as "Cannot reproduce", but of course feel free to drop a comment if you experience this again.

**Closed by ForNeVeR** 2023-06-11 20:32 UTC
Labels: kind:bug

**Comment by seghier** [comment] 2023-06-11 20:51
Than you
I am not sure but i think it was a conflict between the old and the new version, because i used both of them in two different tools in the same software.
