### ISSUE TITLE
\angle symbol is not working

### ISSUE THREAD

**Issue by pavledev** [ForNeVeR/xaml-math#282] opened 2020-10-08 18:18 UTC
I tried to display angle symbol but when I run app only red rectangle is displayed.
formulaControl.Formula = @"\oint_{S}\vec{E}d\vec{S}=\oint_{S}EdS*\angle (\vec{E},d\vec{S})=\oint_{S}EdScos, 0=\oint_{S}Eds=E\oint_{S}dS=ES";

**Comment by FoggyFinder** [comment] 2020-10-08 18:22
Duplicate of #127

**Comment by pavledev** [comment] 2020-10-08 18:25
Can you please fix that issue?

**Comment by pavledev** [comment] 2020-10-08 18:46
Are this two things below required? @FoggyFinder
https://github.com/opencollab/jlatexmath/blob/c9a962cc7cbd2506d46c21eda93c1a4278b1c5ef/jlatexmath/src/main/resources/org/scilab/forge/jlatexmath/TeXFormulaSettings.xml#L605
https://github.com/opencollab/jlatexmath/blob/c9a962cc7cbd2506d46c21eda93c1a4278b1c5ef/jlatexmath/src/main/resources/org/scilab/forge/jlatexmath/TeXSymbols.xml#L185

**Comment by FoggyFinder** [comment] 2020-10-08 19:12
Perhaps. Why can't you experiment with code in a bit and find it out?

**Comment by pavledev** [comment] 2020-10-08 21:40
@FoggyFinder I tried to copy that two lines and after building I tried to run WpfMath.Example and I got error: WpfMath.SymbolMappingNotFoundException: 'Cannot find mapping for the symbol with name 'angle'.'

**Comment by pavledev** [comment] 2020-10-08 21:59
@FoggyFinder Can you please help me to add \angle symbol?

**Comment by ForNeVeR** [comment] 2020-10-18 10:00
I have skimmed through the fonts we're using and found no angle symbol there. Seems we'll need additional font for that.

**Comment by ForNeVeR** [comment] 2020-10-18 11:41
Also I've checked the Computer Modern font sources, and haven't find the angle character there. Does it even exists?

**Comment by FoggyFinder** [comment] 2020-10-18 12:01
`jsMath` uses `msam10` and `msbm10` fonts for it

http://www.math.union.edu/~dpvc/jsMath/symbols/AMSsymbols.html

**Comment by rstm-sf** [comment] 2020-10-25 16:19
@pavledev  if necessary, there is a temporary solution in the form of using a similar command `\text{∠}` and font changes, for example [from the suggested](https://www.fileformat.info/info/unicode/char/2220/fontsupport.htm)
![image](https://user-images.githubusercontent.com/2669927/97112348-9959b300-1705-11eb-8b10-f3c6f6db7e9c.png)

**Comment by Abdel-Fattah-Radwan** [comment] 2020-11-18 23:40
Is there's any chance this will hopefully be fixed? I sadly lack the expertise to fix it myself.

**Comment by ForNeVeR** [comment] 2023-05-18 19:46
Duplicate of #127.

**Closed by ForNeVeR** 2023-05-18 19:46 UTC
Labels: kind:feature
